-- Apex Persona initial schema for MySQL 8.0.16+ / MariaDB 10.4+.
-- IDs are generated by the Node application so this schema is portable across DirectAdmin hosts.

CREATE TABLE IF NOT EXISTS persona_specs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  learning_goal TEXT NOT NULL,
  role_description TEXT NULL,
  scope_json JSON NOT NULL,
  risk_level ENUM('low','medium','high','regulated') NOT NULL DEFAULT 'medium',
  freshness_policy_json JSON NOT NULL,
  source_policy_json JSON NOT NULL,
  learning_policy_json JSON NOT NULL,
  status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
  created_by VARCHAR(200) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY persona_specs_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS domains (
  id CHAR(36) NOT NULL PRIMARY KEY,
  parent_id CHAR(36) NULL,
  name VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  description TEXT NULL,
  volatility_class ENUM('stable','moderate','high') NOT NULL DEFAULT 'moderate',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT domains_parent_fk FOREIGN KEY (parent_id) REFERENCES domains(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS persona_domains (
  persona_spec_id CHAR(36) NOT NULL,
  domain_id CHAR(36) NOT NULL,
  priority SMALLINT NOT NULL DEFAULT 50,
  scope_note TEXT NULL,
  PRIMARY KEY (persona_spec_id, domain_id),
  CONSTRAINT persona_domains_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE CASCADE,
  CONSTRAINT persona_domains_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS learning_runs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  run_type ENUM('initial_build','refresh','manual_import','revalidation') NOT NULL DEFAULT 'initial_build',
  status ENUM('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
  config_snapshot_json JSON NOT NULL,
  summary_json JSON NOT NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP(3) NULL,
  completed_at TIMESTAMP(3) NULL,
  created_by VARCHAR(200) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY runs_persona_started_idx (persona_spec_id, started_at),
  KEY runs_status_idx (status),
  CONSTRAINT runs_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS query_plans (
  id CHAR(36) NOT NULL PRIMARY KEY,
  learning_run_id CHAR(36) NOT NULL,
  persona_spec_id CHAR(36) NOT NULL,
  objective TEXT NOT NULL,
  topic VARCHAR(500) NOT NULL,
  query_text TEXT NOT NULL,
  query_type ENUM('definition','official','research','procedure','case_study','failure_mode','critique','current_update') NOT NULL,
  target_source_classes JSON NOT NULL,
  priority SMALLINT NOT NULL DEFAULT 50,
  status ENUM('planned','approved','executed','rejected') NOT NULL DEFAULT 'planned',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY query_plans_run_priority_idx (learning_run_id, priority),
  FULLTEXT KEY query_plans_text_fts (query_text),
  CONSTRAINT query_plans_run_fk FOREIGN KEY (learning_run_id) REFERENCES learning_runs(id) ON DELETE CASCADE,
  CONSTRAINT query_plans_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS source_publishers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  canonical_name VARCHAR(300) NOT NULL,
  domain VARCHAR(255) NULL UNIQUE,
  source_class ENUM('official','academic','professional','publisher','expert','community','unknown','spam') NOT NULL DEFAULT 'unknown',
  base_reputation_score DECIMAL(4,3) NOT NULL DEFAULT 0.150,
  reputation_reason TEXT NOT NULL,
  ownership_json JSON NOT NULL,
  policy_flags_json JSON NOT NULL,
  last_reviewed_at TIMESTAMP(3) NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY publishers_class_idx (source_class, base_reputation_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sources (
  id CHAR(36) NOT NULL PRIMARY KEY,
  publisher_id CHAR(36) NULL,
  canonical_url TEXT NULL,
  canonical_url_hash CHAR(64) NULL UNIQUE,
  source_type ENUM('web_page','pdf','paper','book','video','podcast','forum_thread','repository','dataset','uploaded_file') NOT NULL,
  title TEXT NULL,
  author_json JSON NOT NULL,
  published_at DATETIME(3) NULL,
  language_code VARCHAR(35) NULL,
  license_json JSON NOT NULL,
  discovery_method ENUM('search','seed_url','manual','api','upload') NOT NULL,
  discovered_from_query_id CHAR(36) NULL,
  status ENUM('discovered','allowed','blocked','fetched','failed','superseded') NOT NULL DEFAULT 'discovered',
  content_hash CHAR(64) NULL,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY sources_publisher_idx (publisher_id),
  KEY sources_type_idx (source_type),
  KEY sources_published_idx (published_at),
  KEY sources_content_hash_idx (content_hash),
  CONSTRAINT sources_publisher_fk FOREIGN KEY (publisher_id) REFERENCES source_publishers(id) ON DELETE SET NULL,
  CONSTRAINT sources_query_fk FOREIGN KEY (discovered_from_query_id) REFERENCES query_plans(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS source_fetches (
  id CHAR(36) NOT NULL PRIMARY KEY,
  source_id CHAR(36) NOT NULL,
  learning_run_id CHAR(36) NOT NULL,
  fetch_method ENUM('http','browser','api','upload','transcript') NOT NULL,
  requested_url TEXT NULL,
  final_url TEXT NULL,
  http_status SMALLINT NULL,
  fetched_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  raw_object_uri TEXT NULL,
  mime_type VARCHAR(200) NULL,
  byte_size BIGINT UNSIGNED NULL,
  content_hash CHAR(64) NULL,
  robots_result ENUM('allowed','denied','unknown','not_applicable') NOT NULL DEFAULT 'unknown',
  error_json JSON NULL,
  parser_version VARCHAR(100) NOT NULL,
  KEY fetches_source_time_idx (source_id, fetched_at),
  KEY fetches_run_idx (learning_run_id),
  KEY fetches_hash_idx (content_hash),
  CONSTRAINT fetches_source_fk FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE RESTRICT,
  CONSTRAINT fetches_run_fk FOREIGN KEY (learning_run_id) REFERENCES learning_runs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS documents (
  id CHAR(36) NOT NULL PRIMARY KEY,
  source_id CHAR(36) NOT NULL,
  fetch_id CHAR(36) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  raw_object_uri TEXT NULL,
  normalized_text_uri TEXT NULL,
  normalized_text LONGTEXT NOT NULL,
  document_hash CHAR(64) NOT NULL,
  word_count INT UNSIGNED NOT NULL DEFAULT 0,
  quality_score DECIMAL(4,3) NULL,
  quality_flags_json JSON NOT NULL,
  language_code VARCHAR(35) NULL,
  normalization_version VARCHAR(100) NOT NULL,
  status ENUM('ready','quarantined','duplicate','rejected','superseded') NOT NULL DEFAULT 'ready',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY documents_source_version_uq (source_id, version_no),
  UNIQUE KEY documents_source_hash_uq (source_id, document_hash),
  KEY documents_hash_idx (document_hash),
  CONSTRAINT documents_source_fk FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE RESTRICT,
  CONSTRAINT documents_fetch_fk FOREIGN KEY (fetch_id) REFERENCES source_fetches(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_sections (
  id CHAR(36) NOT NULL PRIMARY KEY,
  document_id CHAR(36) NOT NULL,
  parent_section_id CHAR(36) NULL,
  sequence_no INT UNSIGNED NOT NULL,
  heading_path TEXT NULL,
  section_title TEXT NULL,
  content_text LONGTEXT NOT NULL,
  start_char INT UNSIGNED NOT NULL,
  end_char INT UNSIGNED NOT NULL,
  token_count INT UNSIGNED NOT NULL DEFAULT 0,
  section_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY sections_document_sequence_uq (document_id, sequence_no),
  KEY sections_hash_idx (section_hash),
  FULLTEXT KEY sections_content_fts (content_text),
  CONSTRAINT sections_document_fk FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE RESTRICT,
  CONSTRAINT sections_parent_fk FOREIGN KEY (parent_section_id) REFERENCES document_sections(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS document_domain_tags (
  id CHAR(36) NOT NULL PRIMARY KEY,
  document_id CHAR(36) NULL,
  section_id CHAR(36) NULL,
  domain_id CHAR(36) NOT NULL,
  confidence DECIMAL(4,3) NOT NULL,
  assigned_by ENUM('model','human','rule') NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY document_tags_domain_idx (domain_id),
  CONSTRAINT document_tags_document_fk FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE RESTRICT,
  CONSTRAINT document_tags_section_fk FOREIGN KEY (section_id) REFERENCES document_sections(id) ON DELETE RESTRICT,
  CONSTRAINT document_tags_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT,
  CONSTRAINT document_tags_one_target CHECK ((document_id IS NOT NULL AND section_id IS NULL) OR (document_id IS NULL AND section_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS knowledge_atoms (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  learning_run_id CHAR(36) NULL,
  atom_type ENUM('concept','claim','procedure','heuristic','case','constraint') NOT NULL,
  canonical_text TEXT NOT NULL,
  summary TEXT NULL,
  subject_text TEXT NULL,
  predicate VARCHAR(500) NULL,
  object_text TEXT NULL,
  context_json JSON NOT NULL,
  assumptions_json JSON NOT NULL,
  metrics_json JSON NOT NULL,
  domain_scope_json JSON NOT NULL,
  initial_status ENUM('unreviewed','extracted','merged','discarded') NOT NULL DEFAULT 'unreviewed',
  current_validation_status ENUM('unreviewed','supported','mixed','disputed','insufficient_evidence','rejected_by_constraint','approved') NOT NULL DEFAULT 'unreviewed',
  canonical_language_code VARCHAR(35) NULL,
  created_by_pipeline_version VARCHAR(100) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY atoms_persona_type_idx (persona_spec_id, atom_type),
  KEY atoms_validation_status_idx (current_validation_status),
  FULLTEXT KEY atoms_canonical_fts (canonical_text),
  CONSTRAINT atoms_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT,
  CONSTRAINT atoms_run_fk FOREIGN KEY (learning_run_id) REFERENCES learning_runs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_versions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  atom_id CHAR(36) NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  canonical_text TEXT NOT NULL,
  context_json JSON NOT NULL,
  change_type ENUM('created','model_revision','human_edit','merge','split','superseded') NOT NULL,
  change_reason TEXT NULL,
  created_by VARCHAR(200) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY atom_versions_number_uq (atom_id, version_no),
  CONSTRAINT atom_versions_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_evidence (
  id CHAR(36) NOT NULL PRIMARY KEY,
  atom_id CHAR(36) NOT NULL,
  document_id CHAR(36) NOT NULL,
  section_id CHAR(36) NULL,
  stance ENUM('supports','contradicts','qualifies','defines','illustrates','mentions') NOT NULL,
  evidence_quote TEXT NOT NULL,
  start_char INT UNSIGNED NULL,
  end_char INT UNSIGNED NULL,
  extraction_confidence DECIMAL(4,3) NULL,
  evidence_type ENUM('opinion','anecdote','guidance','case_study','dataset','experiment','study','standard','primary_record') NOT NULL,
  independence_group VARCHAR(500) NULL,
  created_by_pipeline_version VARCHAR(100) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY atom_evidence_stance_idx (atom_id, stance),
  KEY atom_evidence_document_idx (document_id),
  CONSTRAINT atom_evidence_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT atom_evidence_document_fk FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE RESTRICT,
  CONSTRAINT atom_evidence_section_fk FOREIGN KEY (section_id) REFERENCES document_sections(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_domains (
  atom_id CHAR(36) NOT NULL,
  domain_id CHAR(36) NOT NULL,
  relevance_score DECIMAL(4,3) NOT NULL,
  assigned_by ENUM('model','human','rule') NOT NULL,
  PRIMARY KEY (atom_id, domain_id),
  CONSTRAINT atom_domains_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT atom_domains_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_clusters (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  cluster_type ENUM('duplicate','similar_claim','contradiction_candidate','procedure_variant') NOT NULL,
  canonical_atom_id CHAR(36) NULL,
  cluster_summary TEXT NOT NULL,
  similarity_method VARCHAR(100) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY clusters_persona_idx (persona_spec_id),
  CONSTRAINT clusters_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT,
  CONSTRAINT clusters_atom_fk FOREIGN KEY (canonical_atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_cluster_members (
  cluster_id CHAR(36) NOT NULL,
  atom_id CHAR(36) NOT NULL,
  similarity_score DECIMAL(5,4) NOT NULL,
  relation ENUM('duplicate','equivalent','variant','possible_contradiction') NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (cluster_id, atom_id),
  CONSTRAINT cluster_members_cluster_fk FOREIGN KEY (cluster_id) REFERENCES atom_clusters(id) ON DELETE RESTRICT,
  CONSTRAINT cluster_members_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS source_reputation_assessments (
  id CHAR(36) NOT NULL PRIMARY KEY,
  publisher_id CHAR(36) NOT NULL,
  domain_id CHAR(36) NULL,
  score DECIMAL(4,3) NOT NULL,
  tier ENUM('A','B','C','D') NOT NULL,
  rationale_json JSON NOT NULL,
  assessment_method ENUM('seed_rule','model','human','feedback_update') NOT NULL,
  valid_from TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  valid_until TIMESTAMP(3) NULL,
  created_by VARCHAR(200) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY reputation_publisher_valid_idx (publisher_id, valid_from),
  CONSTRAINT reputation_publisher_fk FOREIGN KEY (publisher_id) REFERENCES source_publishers(id) ON DELETE RESTRICT,
  CONSTRAINT reputation_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS validation_runs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  atom_id CHAR(36) NULL,
  cluster_id CHAR(36) NULL,
  validation_type ENUM('source_score','corroboration','conflict','constraint','recency','full_score') NOT NULL,
  pipeline_version VARCHAR(100) NOT NULL,
  input_snapshot_json JSON NOT NULL,
  output_json JSON NOT NULL,
  status ENUM('completed','failed','needs_review') NOT NULL,
  executed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT validation_runs_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT,
  CONSTRAINT validation_runs_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT validation_runs_cluster_fk FOREIGN KEY (cluster_id) REFERENCES atom_clusters(id) ON DELETE RESTRICT,
  CONSTRAINT validation_runs_target CHECK (atom_id IS NOT NULL OR cluster_id IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_validation_scores (
  id CHAR(36) NOT NULL PRIMARY KEY,
  atom_id CHAR(36) NOT NULL,
  score_version VARCHAR(100) NOT NULL,
  source_quality_score DECIMAL(4,3) NOT NULL,
  evidence_strength_score DECIMAL(4,3) NOT NULL,
  corroboration_score DECIMAL(4,3) NOT NULL,
  recency_score DECIMAL(4,3) NOT NULL,
  constraint_consistency_score DECIMAL(4,3) NOT NULL,
  conflict_penalty DECIMAL(4,3) NOT NULL,
  final_confidence_score DECIMAL(4,3) NOT NULL,
  confidence_band ENUM('high','supported','tentative','weak') NOT NULL,
  validation_status ENUM('supported','mixed','disputed','insufficient_evidence','rejected_by_constraint','approved') NOT NULL,
  explanation_json JSON NOT NULL,
  current_marker TINYINT NULL DEFAULT 1,
  calculated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY atom_validation_one_current_score (atom_id, current_marker),
  KEY scores_confidence_idx (confidence_band, final_confidence_score),
  CONSTRAINT atom_scores_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS claim_relations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  from_atom_id CHAR(36) NOT NULL,
  to_atom_id CHAR(36) NOT NULL,
  relation_type ENUM('supports','contradicts','qualifies','supersedes','derived_from','same_as','depends_on') NOT NULL,
  strength_score DECIMAL(4,3) NOT NULL,
  reason_json JSON NOT NULL,
  status ENUM('proposed','verified','rejected') NOT NULL DEFAULT 'proposed',
  verified_by VARCHAR(200) NULL,
  verified_at TIMESTAMP(3) NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY relations_from_idx (from_atom_id, relation_type),
  KEY relations_to_idx (to_atom_id, relation_type),
  CONSTRAINT relations_from_fk FOREIGN KEY (from_atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT relations_to_fk FOREIGN KEY (to_atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS persona_constraints (
  id CHAR(36) NOT NULL PRIMARY KEY,
  domain_id CHAR(36) NULL,
  constraint_type ENUM('formal_rule','standard','legal_rule','mathematical','physical','platform_policy','safety') NOT NULL,
  statement TEXT NOT NULL,
  structured_rule_json JSON NOT NULL,
  authority_level ENUM('hard','strong','advisory') NOT NULL,
  effective_from TIMESTAMP(3) NULL,
  effective_to TIMESTAMP(3) NULL,
  status ENUM('active','superseded','withdrawn') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT persona_constraints_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS constraint_evidence (
  id CHAR(36) NOT NULL PRIMARY KEY,
  constraint_id CHAR(36) NOT NULL,
  document_id CHAR(36) NOT NULL,
  section_id CHAR(36) NULL,
  evidence_quote TEXT NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY constraint_evidence_constraint_idx (constraint_id, document_id),
  CONSTRAINT constraint_evidence_constraint_fk FOREIGN KEY (constraint_id) REFERENCES persona_constraints(id) ON DELETE RESTRICT,
  CONSTRAINT constraint_evidence_document_fk FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE RESTRICT,
  CONSTRAINT constraint_evidence_section_fk FOREIGN KEY (section_id) REFERENCES document_sections(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_constraint_checks (
  id CHAR(36) NOT NULL PRIMARY KEY,
  atom_id CHAR(36) NOT NULL,
  constraint_id CHAR(36) NOT NULL,
  result ENUM('consistent','conflict','not_applicable','uncertain') NOT NULL,
  explanation TEXT NOT NULL,
  checker_version VARCHAR(100) NOT NULL,
  checked_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY constraint_checks_atom_idx (atom_id, result),
  CONSTRAINT constraint_checks_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT constraint_checks_constraint_fk FOREIGN KEY (constraint_id) REFERENCES persona_constraints(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS review_tasks (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  target_type ENUM('source','document','atom','cluster','relation','constraint') NOT NULL,
  target_id CHAR(36) NOT NULL,
  reason_code ENUM('high_risk','source_conflict','low_evidence','extraordinary_claim','manual_sampling','model_error','user_dispute') NOT NULL,
  priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  status ENUM('open','assigned','approved','rejected','edited','deferred') NOT NULL DEFAULT 'open',
  assigned_to VARCHAR(200) NULL,
  decision_json JSON NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  resolved_at TIMESTAMP(3) NULL,
  KEY review_queue_idx (status, priority, created_at),
  KEY review_persona_idx (persona_spec_id, status),
  CONSTRAINT review_tasks_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS embeddings (
  id CHAR(36) NOT NULL PRIMARY KEY,
  entity_type ENUM('document','section','atom','concept','playbook') NOT NULL,
  entity_id CHAR(36) NOT NULL,
  embedding_model VARCHAR(200) NOT NULL,
  vector_store_key VARCHAR(500) NULL,
  content_hash CHAR(64) NOT NULL,
  dimension INT UNSIGNED NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  superseded_at TIMESTAMP(3) NULL,
  UNIQUE KEY embeddings_entity_hash_uq (entity_type, entity_id, embedding_model, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS concepts (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NULL,
  preferred_label VARCHAR(500) NOT NULL,
  definition TEXT NULL,
  domain_id CHAR(36) NULL,
  status ENUM('candidate','active','deprecated','merged') NOT NULL DEFAULT 'candidate',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY concepts_persona_label_idx (persona_spec_id, preferred_label(191)),
  FULLTEXT KEY concepts_label_fts (preferred_label, definition),
  CONSTRAINT concepts_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT,
  CONSTRAINT concepts_domain_fk FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS concept_aliases (
  id CHAR(36) NOT NULL PRIMARY KEY,
  concept_id CHAR(36) NOT NULL,
  alias_text VARCHAR(500) NOT NULL,
  language_code VARCHAR(35) NOT NULL DEFAULT 'und',
  alias_type ENUM('synonym','abbreviation','legacy_term','translation') NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY concept_alias_uq (concept_id, alias_text(191), language_code),
  CONSTRAINT concept_alias_concept_fk FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atom_concepts (
  atom_id CHAR(36) NOT NULL,
  concept_id CHAR(36) NOT NULL,
  role ENUM('subject','object','condition','method','outcome','metric','risk') NOT NULL,
  relevance_score DECIMAL(4,3) NOT NULL,
  assigned_by ENUM('model','human','rule') NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (atom_id, concept_id, role),
  CONSTRAINT atom_concepts_atom_fk FOREIGN KEY (atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT,
  CONSTRAINT atom_concepts_concept_fk FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS concept_relations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  from_concept_id CHAR(36) NOT NULL,
  to_concept_id CHAR(36) NOT NULL,
  relation_type ENUM('is_a','part_of','requires','causes','improves','reduces','measured_by','applies_to','related_to') NOT NULL,
  confidence_score DECIMAL(4,3) NOT NULL,
  supporting_atom_id CHAR(36) NULL,
  status ENUM('proposed','active','disputed','deprecated') NOT NULL DEFAULT 'proposed',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT concept_relations_from_fk FOREIGN KEY (from_concept_id) REFERENCES concepts(id) ON DELETE RESTRICT,
  CONSTRAINT concept_relations_to_fk FOREIGN KEY (to_concept_id) REFERENCES concepts(id) ON DELETE RESTRICT,
  CONSTRAINT concept_relations_atom_fk FOREIGN KEY (supporting_atom_id) REFERENCES knowledge_atoms(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS retrieval_profiles (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  name VARCHAR(200) NOT NULL DEFAULT 'default_evidence_first',
  task_type VARCHAR(100) NULL,
  min_confidence_band ENUM('weak','tentative','supported','high') NOT NULL DEFAULT 'supported',
  max_results SMALLINT UNSIGNED NOT NULL DEFAULT 10,
  recency_preference DECIMAL(4,3) NOT NULL DEFAULT 0.500,
  source_diversity_required BOOLEAN NOT NULL DEFAULT TRUE,
  include_conflicts BOOLEAN NOT NULL DEFAULT TRUE,
  allowed_source_classes_json JSON NOT NULL,
  reranking_config_json JSON NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY retrieval_profile_name_uq (persona_spec_id, name),
  CONSTRAINT retrieval_profiles_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS retrieval_logs (
  id CHAR(36) NOT NULL PRIMARY KEY,
  persona_spec_id CHAR(36) NOT NULL,
  retrieval_profile_id CHAR(36) NULL,
  query_text TEXT NOT NULL,
  query_context_json JSON NOT NULL,
  retrieved_entity_type ENUM('atom','section','concept','case','procedure') NOT NULL,
  retrieved_entity_id CHAR(36) NOT NULL,
  result_rank INT UNSIGNED NOT NULL,
  semantic_score DECIMAL(6,5) NULL,
  confidence_score DECIMAL(4,3) NULL,
  rerank_score DECIMAL(6,5) NULL,
  retrieved_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY retrieval_persona_time_idx (persona_spec_id, retrieved_at),
  KEY retrieval_entity_idx (retrieved_entity_type, retrieved_entity_id),
  CONSTRAINT retrieval_logs_persona_fk FOREIGN KEY (persona_spec_id) REFERENCES persona_specs(id) ON DELETE RESTRICT,
  CONSTRAINT retrieval_logs_profile_fk FOREIGN KEY (retrieval_profile_id) REFERENCES retrieval_profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
